// GENERATED by scripts/model-metadata.mjs — do not edit by hand.
// Source: scripts/model-metadata.snapshot.json (refreshed from models.dev).

import type { ModelPrice } from "./cost.js";

export interface ModelMeta {
  /** $ / 1M input+output tokens */
  price?: ModelPrice;
  /** maximum context window in tokens */
  contextWindow?: number;
}

/** Committed metadata snapshot — merged under user `prices` overrides. */
export const MODEL_METADATA: Record<string, ModelMeta> = {
  "anthropic/claude-3-5-haiku": { price: { input: 0.8, output: 4 } },
  "anthropic/claude-3-5-sonnet": { price: { input: 3, output: 15 }, contextWindow: 200000 },
  "anthropic/claude-3-opus": { price: { input: 15, output: 75 } },
  "anthropic/claude-haiku-4": { price: { input: 1, output: 5 } },
  "anthropic/claude-opus-4": { price: { input: 15, output: 75 }, contextWindow: 200000 },
  "anthropic/claude-sonnet-4": { price: { input: 3, output: 15 }, contextWindow: 200000 },
  "deepseek/deepseek-chat": { price: { input: 0.27, output: 1.1 }, contextWindow: 65536 },
  "deepseek/deepseek-reasoner": { price: { input: 0.55, output: 2.19 }, contextWindow: 65536 },
  "google/gemini-1.5-flash": { price: { input: 0.075, output: 0.3 } },
  "google/gemini-1.5-pro": { price: { input: 1.25, output: 5 } },
  "google/gemini-2.0-flash": { price: { input: 0.1, output: 0.4 } },
  "google/gemini-2.5-flash": { price: { input: 0.15, output: 0.6 }, contextWindow: 1048576 },
  "google/gemini-2.5-pro": { price: { input: 1.25, output: 10 }, contextWindow: 1048576 },
  "meta/llama-3.1-70b": { price: { input: 0.59, output: 0.79 } },
  "mistral/mistral-large": { price: { input: 2, output: 6 } },
  "mistral/mistral-small": { price: { input: 0.2, output: 0.6 } },
  "openai/gpt-4.1": { price: { input: 2, output: 8 }, contextWindow: 1047576 },
  "openai/gpt-4.1-mini": { price: { input: 0.4, output: 1.6 } },
  "openai/gpt-4.1-nano": { price: { input: 0.1, output: 0.4 } },
  "openai/gpt-4o": { price: { input: 2.5, output: 10 }, contextWindow: 128000 },
  "openai/gpt-4o-mini": { price: { input: 0.15, output: 0.6 }, contextWindow: 128000 },
  "openai/o1": { price: { input: 15, output: 60 } },
  "openai/o1-mini": { price: { input: 3, output: 12 } },
  "openai/o1-preview": { price: { input: 15, output: 60 } },
  "qwen/qwen-max": { price: { input: 2.4, output: 9.6 } },
  "qwen/qwen-plus": { price: { input: 0.4, output: 1.2 } },
  "qwen/qwen-turbo": { price: { input: 0.05, output: 0.2 } },
};
